language: python
cache:
- bundler
before_script:
script:
- gulp build
deploy:
  provider: heroku
  api_key:
    secure: ggS6dU6bxO1zTwLvL/bgOhqJ0aIJJoi/E4z9u6Ud5yO05p5d+raMHgEG0N7wcZTPfUwxCmBxocVB4M+SBqk8XMre6q49GG2wBKXnf9cDhQzOZq9vlXWShRvT6COC45hULxwWclDJlaNrBjU1KquytxfMWsfL5ka4f8QgzS5vvv13qouCHhs61uS71aAXIU76jRNUUJmnxwl3OMisTW5WpRhmHVl4UUSPtrzzzsBi31LDUQxqJgXVq5bhqInS+7+m2CZA42vapW85Eynyzl88iyjBU7yn0J7aZcv8NERqZDM/8xZcPefiir2oJxPSLKVxQnMfmrTH6wLRDvNwu8l40aETps73NMwMRYx2yXnrXZpLnpUEubebKHBxng6MECWj8rP/L7QKb9oV8yPfjjX0rw9TQjI6RZjjq93nsELz6s1Bso8unoFm1E1EZgwuznMearcEVrpe4yH6WSdYJT0PcrErJr3W2y5ZAeWwm26ol13aWV8GWIC8W4WqKPEuA0rZ4zDDOZ1NjSyFrsK6+cnofH8pjsA1GuB1o7D3FKXOJX8RqCeF4+EwyQ4Tuj1B8pEhTMSNGnPlQOwE3WMSsz3IpmjczeITJB2g/VpFcG31qsU5Ji0D+7N9VTvWQZcFDrL1pG+BlZ7n9kz/uaQJF2ZgCF3dNxKmLfTmafX+0q5TpjY=
  app: ping--pong
  on:
    repo: felipeluizsoares/rails-test-app

